version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: myminio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data/
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

  mc:
    image: minio/mc:latest
    depends_on:
     - minio
    entrypoint: >
     /bin/sh -c "
     /usr/bin/mc alias set myminio http://myminio:9000 minioadmin minioadmin;
     /usr/bin/mc mb myminio/my-django-bucket;
     /usr/bin/mc policy set public myminio/my-django-bucket;
     "

volumes:
  postgres_data:
  minio_data:
