# Generated by Django 5.0.3 on 2024-04-05 14:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_basepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepage",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
